CREATE DATABASE shop_platform;
USE shop_platform;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN phone VARCHAR(20) NULL AFTER email,
ADD COLUMN address VARCHAR(255) NULL AFTER phone,
ADD COLUMN payment_details JSON NULL AFTER password,
ADD COLUMN avatar VARCHAR(255) NULL AFTER payment_details;


CREATE TABLE shops (
  id INT AUTO_INCREMENT PRIMARY KEY,
  shop_name VARCHAR(150) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE shops
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN logo VARCHAR(255);


CREATE TABLE shop_staff (
  id INT AUTO_INCREMENT PRIMARY KEY,
  shop_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin', 'staff') DEFAULT 'staff',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE
);

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  shop_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE
);

ALTER TABLE products
ADD COLUMN category VARCHAR(100),
ADD COLUMN stock INT DEFAULT 0,
ADD COLUMN sku VARCHAR(100),
ADD COLUMN discount DECIMAL(5,2) DEFAULT 0,
ADD COLUMN main_image VARCHAR(255),
ADD COLUMN status ENUM('active','inactive') DEFAULT 'active';

ALTER TABLE products
ADD COLUMN brand VARCHAR(100);

CREATE TABLE product_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);



